before_script:
  - git submodule update --init

stages:
  - test
  - build
  - deploy

test:lint:
  stage: test
  image: ziirish/python:2.7
  script:
  - pip install flake8 pylint
  - make flake8
  tags:
  - lint
  except:
  - tags

test:py2.7:
  stage: test
  image: ziirish/python:2.7
  script:
  - /bin/bash test/run_tests.sh
  tags:
  - docker
  except:
  - tags

test:py3.4:
  stage: test
  image: ziirish/python:3.4
  script:
  - /bin/bash test/run_tests.sh
  tags:
  - docker
  except:
  - tags

build:py2:
  stage: build
  script:
  - /bin/bash test/run_build.sh
  tags:
  - build
  only:
  - master
  - demo
  artifacts:
    path:
    - dist/

build:py3:
  stage: build
  image: ziirish/python:3.4
  script:
  - /bin/bash test/run_build.sh
  tags:
  - build
  only:
  - master
  artifacts:
    paths:
    - dist/

deploy:demo:
  stage: deploy
  script:
  - find docker/ -name "install" | xargs sed -i "s/@build@/$(git rev-parse HEAD)/"
  - cp -r docker/ /srv/demo/
  - cd /srv/demo/docker/
  - docker-compose build
  - docker-compose stop
  - docker-compose rm -f
  - docker-compose up -d
  tags:
  - deploy
  only:
  - rc
  - demo
