
stages:
  - test
  - build
  - deploy

py2.7:
  stage: test
  image: python:2.7
  script:
  - /bin/bash test/run_tests.sh
  tags:
  - docker
  except:
  - tags

py3.4:
  stage: test
  image: python:3.4
  script:
  - /bin/bash test/run_tests.sh
  tags:
  - docker
  except:
  - tags

build-dev:
  stage: build
  script:
  - /bin/bash test/run_build.sh
  tags:
  - build
  only:
  - master
