redis:
  restart: always
  image: redis

mariadb:
  restart: always
  image: mariadb
  environment:
    - MYSQL_USER=burpui
    - MYSQL_PASSWORD=burpui
    - MYSQL_DATABASE=burpuidb
# Additionally, you may want to persist data
# volumes:
#   - /var/lib/buistore:/var/lib/mysql

burpui:
  restart: always
  image: registry.ziirish.me/ziirish/burp-ui:latest
  links:
    - redis
    - mariadb
  ports:
    - 127.0.0.1:5000:5000
  volumes:
    - /etc/burp:/etc/burp
    - /var/spool/burp:/var/spool/burp
# Additionally, you can override some default settings
#  environment:
#    - BURPUI_CONFIG=/etc/burp/burpui.cfg
#    - BURPUI_VERBOSE=0
#    - BURPUI_CLIENT_NAME=bui
#    - BURPUI_UID=5337
#    - BURPUI_GID=5337
#    - BURP_CLIENT_CONFIG=/tmp/burp.conf
#    - BURP_SERVER_CONFIG=/etc/burp/burp-server.conf
#    - DATABASE_URL=mysql://burpui:burpui@mariadb/burpuidb
#    - REDIS_SERVER=redis:6379
#    - BURP_SERVER_ADDR=auto
#    - TIMEZONE=Europe/Paris
