version: '2'

services:
  redis:
    restart: always
    image: redis

  #mariadb:
  #  restart: always
  #  image: mariadb
  #  environment:
  #    - MYSQL_USER=burpui
  #    - MYSQL_PASSWORD=burpui
  #    - MYSQL_DATABASE=burpuidb
  #    - MYSQL_RANDOM_ROOT_PASSWORD=yes
  ## Additionally, you may want to persist data
  ## volumes:
  ##   - /var/lib/buistore/mariadb:/var/lib/mysql

  pgsql:
    restart: always
    image: registry.ziirish.me/ziirish/burp-ui/pgsql:0.5.1
  ## Additionally, you may want to persist data
  ## volumes:
  ##   - /var/lib/buistore/pgsql:/var/lib/postgresql/data

  burp-server:
    restart: always
    image: registry.ziirish.me/ziirish/burp-ui/burp:latest
    ports:
      - 127.0.0.1:4971:4971
      - 127.0.0.1:4972:4972
    volumes:
      - /etc/burp:/etc/burp
      - /var/spool/burp:/var/spool/burp
  # Additionally, you can override some default settings
  #  environment:
  #    - BURPUI_UID=5337
  #    - BURPUI_GID=5337
  #    - TIMEZONE=Europe/Paris

  burpui:
    restart: always
    image: registry.ziirish.me/ziirish/burp-ui:0.5.1-py3.6
    depends_on:
      - burp-server
      - redis
      - pgsql
    ports:
      - 127.0.0.1:5000:8000
    volumes:
      - /etc/burp:/etc/burp
      - /var/spool/burp:/var/spool/burp
  # Additionally, you can override some default settings
  #  environment:
  #    - BURPUI_CONFIG=/etc/burp/burpui.cfg
  #    - BURPUI_VERBOSE=0
  #    - BURPUI_CLIENT_NAME=bui
  #    - BURPUI_UID=5337
  #    - BURPUI_GID=5337
  #    - BURPUI_PLUGINS=none
  #    - BURPUI_WS_WORKERS=2
  #    - BURPUI_RP_SCHEME=https
  #    - BURP_CLIENT_CONFIG=/tmp/burp.conf
  #    - BURP_SERVER_CONFIG=/etc/burp/burp-server.conf
  #    - DATABASE_URL=postgresql://burpui:burpui@pgsql/burpuidb
  #    - GUNICORN_WORKERS=2
  #    - REDIS_SERVER=redis:6379
  #    - BURP_SERVER_ADDR=burp-server
  #    - TIMEZONE=Europe/Paris
